development:
  adapter: postgresql
  database: sample_app_development
  host: localhost

test:
  adapter: postgresql
  database: sample_app_test
  host: localhost

production:
  adapter: postgresql
  database: sample_app_production
  host: localhost